adlist.o: adlist.c adlist.h zmalloc.h
ae.o: ae.c ae.h monotonic.h fmacros.h anet.h redisassert.h redis_config.h \
 zmalloc.h ae_epoll.c
ae_epoll.o: ae_epoll.c
ae_evport.o: ae_evport.c
ae_kqueue.o: ae_kqueue.c
ae_select.o: ae_select.c
anet.o: anet.c fmacros.h anet.h util.h ../deps/hiredis/hiredis.h \
 ../deps/hiredis/read.h ../deps/hiredis/sds.h ../deps/hiredis/alloc.h
config.o: config.c config.h redis_config.h sds.h zmalloc.h logger.h
crc16.o: crc16.c
debug.o: debug.c
dict.o: dict.c fmacros.h redis_config.h dict.h zmalloc.h redisassert.h \
 monotonic.h
endianconv.o: endianconv.c
logger.o: logger.c logger.h config.h redis_config.h sds.h
main.o: main.c zmalloc.h
monotonic.o: monotonic.c monotonic.h fmacros.h redisassert.h \
 redis_config.h
mt19937-64.o: mt19937-64.c mt19937-64.h
rax.o: rax.c rax.h redisassert.h redis_config.h rax_malloc.h zmalloc.h
redisassert.o: redisassert.c
sds.o: sds.c sds.h sdsalloc.h zmalloc.h
siphash.o: siphash.c
strl.o: strl.c
tatiana.o: tatiana.c ae.h monotonic.h fmacros.h anet.h zmalloc.h sds.h \
 util.h ../deps/hiredis/hiredis.h
util.o: util.c sds.h util.h ../deps/hiredis/hiredis.h \
 ../deps/hiredis/read.h ../deps/hiredis/sds.h ../deps/hiredis/alloc.h
zmalloc.o: zmalloc.c fmacros.h redis_config.h zmalloc.h atomicvar.h
